---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodes
  - tensorfusionconnections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodes/finalizers
  - tensorfusionconnections/finalizers
  verbs:
  - update
- apiGroups:
  - tensor-fusion.ai
  resources:
  - gpunodes/status
  - tensorfusionconnections/status
  verbs:
  - get
  - patch
  - update
